language: node_js
node_js:
  - "12"

install:
  - npm install -g coveralls
  - npm install
  - npm install class-transformer@0.3 @bluelibs/logger-bundle

script:
  - npm test
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true # ignore coveralls error
